apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: compliance-labels
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod", "Deployment"]
  parameters:
    labels:
    - key: "compliance.status"
      allowedRegex: "^(scanned|approved)$"
